app/routes.py
from flask import Blueprint, render_template, request, redirect, url_for, flash, abort, jsonify, send_file, current_app, make_response, session
from flask_login import login_user, logout_user, login_required, current_user
from flask_mail import Message
from functools import wraps
from datetime import datetime
from werkzeug.utils import secure_filename
from sqlalchemy import extract, func
from time import time
from datetime import timedelta, date
import os
import requests
from app.extensions import db, login_manager, mail
from app.models import Usuario, Libro, Prestamo, Reserva, Favorito, HistorialReporte
from app.forms import RegistroForm, LibroForm, EditarLibroForm, EditarReservaForm, NuevaReservaForm, PrestamoForm, ReservaLectorForm, AgregarLectorPresencialForm,  EditarUsuarioForm
from app.utils import verificar_token, generar_token, generar_reporte_con_plantilla, generar_reporte_populares, generar_reporte_prestados
from app.libro import prestar_libro, devolver_libro
from PIL import Image

def nocache(view):
    @wraps(view)
    def no_cache(*args, **kwargs):
        response = make_response(view(*args, **kwargs))
        response.headers["Cache-Control"] = "no-store, no-cache, must-revalidate, post-check=0, pre-check=0, max-age=0"
        response.headers["Pragma"] = "no-cache"
        response.headers["Expires"] = "0"
        return response
    return no_cache


main = Blueprint('main', __name__)
login_manager.login_view = 'main.login'

@login_manager.user_loader
def load_user(user_id):
    return Usuario.query.get(int(user_id))

def roles_requeridos(*roles):
    def decorator(f):
        @wraps(f)
        def decorated_function(*args, **kwargs):
            if not current_user.is_authenticated:
                return login_manager.unauthorized()
            if current_user.rol not in roles:
                abort(403)
            return f(*args, **kwargs)
        return decorated_function
    return decorator

@main.before_app_request
def actualizar_reservas_vencidas():
    hoy = date.today()

    reservas_vencidas = Reserva.query.filter(
        Reserva.estado == 'activa',
        Reserva.fecha_expiracion < hoy
    ).all()

    for reserva in reservas_vencidas:
        reserva.estado = 'vencida'
        if reserva.libro:
            reserva.libro.cantidad_disponible += 1
            reserva.libro.actualizar_estado()
        current_app.logger.info(f"Reserva #{reserva.id} marcada como vencida.")

    if reservas_vencidas:
        db.session.commit()

@main.before_app_request
def marcar_prestamos_atrasados():
    hoy = date.today()
    prestamos = Prestamo.query.filter(
        Prestamo.estado == 'activo',
        Prestamo.fecha_devolucion_esperada < hoy
    ).all()

    for prestamo in prestamos:
        prestamo.estado = 'atrasado'
        current_app.logger.info(f"Préstamo #{prestamo.id} marcado como atrasado.")
    
    if prestamos:
        db.session.commit()


@main.route('/')
@nocache
def index():
    page = request.args.get('page', 1, type=int)
    libros = Libro.query.filter(Libro.estado != 'eliminado').paginate(page=page, per_page=12)
    # Detectar rol actual (si hay usuario logueado)
    rol = current_user.rol if current_user.is_authenticated else None

    return render_template('index.html', libros=libros, rol=rol)


@main.route('/registro', methods=['GET', 'POST'])
def registro():
    form = RegistroForm()
    if form.validate_on_submit():
        # Obtener todos los datos del formulario
        nombre = form.nombre.data
        apellido = form.apellido.data
        correo = form.correo.data
        documento = form.documento.data
        direccion = form.direccion.data
        telefono = form.telefono.data
        fecha_nacimiento = form.fecha_nacimiento.data
        password = form.password.data

        # Validar duplicados extra (opcional, ya validado en form)
        if Usuario.query.filter_by(correo=correo).first():
            flash('Correo no disponible.', 'danger')
            return redirect(url_for('main.registro'))
        if Usuario.query.filter_by(documento=documento).first():
            flash('Número de documento ya registrado.', 'danger')
            return redirect(url_for('main.registro'))

        # Crear usuario
        nuevo_usuario = Usuario(
            nombre=nombre,
            apellido=apellido,
            correo=correo,
            documento=documento,
            direccion=direccion,
            telefono=telefono,
            fecha_nacimiento=fecha_nacimiento,
            rol='lector',
            activo=True
        )

        # Generar llave_prestamo de préstamo y contraseña
        nuevo_usuario.generar_llave_prestamo()
        nuevo_usuario.set_password(password)

        # Guardar en base de datos
        db.session.add(nuevo_usuario)
        db.session.commit()

        flash('Registro exitoso. Ya puedes iniciar sesión.', 'success')
        return redirect(url_for('main.login'))

    return render_template('registro.html', form=form)

@main.route('/login', methods=['GET', 'POST'])
@nocache
def login():
    if current_user.is_authenticated:
        # Redirige según el rol si ya tiene sesión activa
        if current_user.rol == 'administrador':
            return redirect(url_for('main.index'))  # O tu ruta real de admin
        elif current_user.rol == 'bibliotecario':
            return redirect(url_for('main.index'))  # Ajusta si es diferente
        elif current_user.rol == 'lector':
            return redirect(url_for('main.catalogo'))
        else:
            return redirect(url_for('main.index'))

    if request.method == 'POST':
        correo = request.form['correo']
        password = request.form['password']

        usuario = Usuario.query.filter_by(correo=correo, activo=True).first()

        if usuario and usuario.check_password(password):
            if usuario.rol == 'lector*':
                flash('Tu cuenta no está habilitada para acceder al sistema.', 'danger')
                return redirect(url_for('main.login'))

            login_user(usuario)
            flash('Has iniciado sesión.', 'success')

            # Redirige según rol
            if usuario.rol == 'administrador':
                return redirect(url_for('main.index'))
            elif usuario.rol == 'bibliotecario':
                return redirect(url_for('main.index'))
            elif usuario.rol == 'lector':
                return redirect(url_for('main.catalogo'))
            else:
                return redirect(url_for('main.index'))

        flash('Correo o contraseña incorrectos', 'danger')
        return redirect(url_for('main.login'))

    return render_template('login.html')


@main.route('/logout')
@login_required
def logout():
    logout_user()
    session.clear()  # Asegura limpiar todo
    flash('Has cerrado sesión.', 'success')
    return redirect(url_for('main.index'))


@main.route('/usuarios')
@login_required
@roles_requeridos('administrador', 'bibliotecario')
@nocache
def lista_usuarios():
    usuarios = Usuario.query.all()
    return render_template('usuarios.html', usuarios=usuarios)

@main.route('/usuarios/<int:usuario_id>/toggle', methods=['POST'])
@login_required
@roles_requeridos('administrador', 'bibliotecario')
@nocache
def toggle_usuario(usuario_id):
    usuario = Usuario.query.get_or_404(usuario_id)

    if usuario.nombre == 'admin':
        flash('No se puede desactivar al administrador principal.', 'error')
        return redirect(url_for('main.lista_usuarios'))

    if current_user.rol == 'bibliotecario' and usuario.rol == 'administrador':
        flash('No tienes permiso para modificar a un administrador.', 'error')
        return redirect(url_for('main.lista_usuarios'))

    usuario.activo = not usuario.activo
    db.session.commit()

    estado = 'activado' if usuario.activo else 'desactivado'
    flash(f"El usuario '{usuario.nombre}' ha sido {estado}.", 'success')
    return redirect(url_for('main.lista_usuarios'))
    
@main.route('/usuarios/<int:usuario_id>/cambiar_rol', methods=['POST'])
@login_required
@roles_requeridos('administrador')
@nocache
def cambiar_rol(usuario_id):
    usuario = Usuario.query.get_or_404(usuario_id)

    if usuario.nombre == 'admin':
        flash('No se puede cambiar el rol del administrador principal.', 'error')
        return redirect(url_for('main.lista_usuarios'))

    nuevo_rol = request.form.get('rol')

    if nuevo_rol not in ['lector', 'bibliotecario', 'administrador']:
        flash('Rol inválido.', 'error')
        return redirect(url_for('main.lista_usuarios'))

    usuario.rol = nuevo_rol
    db.session.commit()
    flash('Rol actualizado correctamente.', 'success')
    return redirect(url_for('main.lista_usuarios'))

@main.route('/admin/inicio', endpoint='inicio')
@login_required
@roles_requeridos('administrador', 'bibliotecario')
@nocache
def admin_inicio():
    return render_template('admin.html', version=time())

@main.route('/admin/inicio-contenido')
@login_required
@roles_requeridos('administrador')
@nocache
def inicio_contenido():
    total_administradores = Usuario.query.filter_by(rol='administrador').count()
    total_lectores = Usuario.query.filter_by(rol='lector').count()
    total_libros = Libro.query.count()
    total_prestamos = Prestamo.query.count() if 'Prestamo' in globals() else 0
    total_reservas = Reserva.query.count() if 'Reserva' in globals() else 0


    return render_template('inicio.html',
        total_administradores=total_administradores,
        total_lectores=total_lectores,
        total_libros=total_libros,
        total_prestamos=total_prestamos,
        total_reservas=total_reservas,

    )

@main.route('/api/datos_libro/<isbn>')
def api_datos_libro(isbn):


templates/partials/usuarios_editar.html
<!DOCTYPE html>
<html lang="es">
<head>
  <meta charset="UTF-8" />
  <title>Editar Usuario</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" />
</head>
<body style="background-color: #f8f9fa;">

  <div class="container py-4">
    <h4 class="mb-4">Editar Usuario</h4>

      <form method="POST" action="{{ url_for('main.editar_usuario', id=usuario.id) }}" class="text-start bg-white p-4 rounded shadow-sm">
        {{ form.hidden_tag() }}

        <div class="mb-3">
          {{ form.nombre.label(class="form-label") }}
          {{ form.nombre(class="form-control") }}
        </div>

        <div class="mb-3">
          {{ form.correo.label(class="form-label") }}
          {{ form.correo(class="form-control") }}
        </div>

        <div class="mb-3">
          {{ form.direccion.label(class="form-label") }}
          {{ form.direccion(class="form-control") }}
        </div>

        <div class="mb-3">
          {{ form.rol.label(class="form-label") }}
          {{ form.rol(class="form-select") }}
        </div>

        <div class="d-flex justify-content-end gap-2">
          <button type="button" class="btn btn-secondary btn-cancelar-usuario">Cancelar</button>
          {{ form.submit(class="btn btn-primary") }}
        </div>
      </form>


  </div>

  <script>
    document.getElementById("form-editar-usuario").addEventListener("submit", function (e) {
      e.preventDefault();

      const datos = {
        id: this.querySelector('[name="id"]').value,
        nombre: this.querySelector('[name="nombre"]').value,
        correo: this.querySelector('[name="correo"]').value,
        direccion: this.querySelector('[name="direccion"]').value,
        rol: this.querySelector('[name="rol"]').value
      };

      console.log("DEBUG:", datos);

      fetch("/admin/usuarios/editar", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(datos)
      })
      .then(res => res.json())
      .then(data => {
        alert(data.mensaje || "Usuario actualizado correctamente");
        window.location.reload();
      })
      .catch(err => {
        console.error("Error:", err);
        alert("Error inesperado");
      });
    });

    document.querySelector(".btn-cancelar-usuario").addEventListener("click", function () {
      window.history.back();
    });
  </script>

  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

templates/partials/usuarios_eliminar.html
<h5>Activar/Desactivar usuarios</h5>
{% for usuario in usuarios %}
  {% if usuario.username != 'admin' %}
    <form action="{{ url_for('main.toggle_usuario', usuario_id=usuario.id) }}" method="POST" class="mb-2 d-flex align-items-center">
      <span class="me-3">{{ usuario.username }}</span>
      <button type="submit" class="btn btn-{{ 'danger' if usuario.activo else 'success' }} btn-sm">
        {{ 'Desactivar' if usuario.activo else 'Activar' }}
      </button>
    </form>
  {% endif %}
{% endfor %}

templates/partials/usuarios_mostrar.html
<h5>Lista de usuarios</h5>
<table class="table table-bordered table-striped">
  <thead>
    <tr><th>ID</th><th>Usuario</th><th>Rol</th><th>Activo</th></tr>
  </thead>
  <tbody>
    {% for usuario in usuarios %}
      <tr>
        <td>{{ usuario.id }}</td>
        <td>{{ usuario.nombre }}</td>
        <td>{{ usuario.rol }}</td>
        <td>{{ 'Sí' if usuario.activo else 'No' }}</td>
      </tr>
    {% endfor %}
  </tbody>
</table>